name: Unit-tests on Linux CPU

on:
  pull_request:
  push:
    branches:
      - site
  workflow_dispatch:

jobs:
  tests:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.12xlarge
      repository: pytorch/pytorch.github.io
      docker-image: cimg/ruby:2.7-node
      script: |
        git config --global --add safe.directory /__w/pytorch.github.io/pytorch.github.io
        set -euxo pipefail

        ## Bundle Install
        bundle config set --local path 'vendor/bundle'
        bundle install

        ## Yarn Install
        yarn install --cache-folder ~/.cache/yarn

        ## Notedown Install
        sudo apt update && sudo apt install python3-pip && sudo -H pip3 install pyrsistent==0.16 notedown pyyaml -Iv nbformat==5.7

        ## Configure Bot
        git config --global user.email "facebook-circleci-bot@users.noreply.github.com"
        git config --global user.name "Website Deployment Script"

        ## Build Jekyll site and push to master
        ./scripts/deploy-site.sh build
